### PR TITLE
Polarization

### PR DESCRIPTION
**Pull request by mdkrzyaniak**
I updated the documentation and provided a pair of examples on the use of the alternative polarization mechanism. This is now no longer an undocumented feature. 
Things still to do:
- [ ] Change fields from `PopBasis` to `PopMode` and have more intuitive names for the different polarization modes
- [ ] Update usage documentation
- [ ] Write a polarization reference page
- [x] Generate some tests
- [x] Include high field polarization i.e. recombination triplet

### CODE REVIEW

**Comment by stestoll** [comment]
Thanks, great to have that documented!

Two things before merging:
- The names `PopBasis`, `'Spin'` and `'Molecular'` are not optimal. Can you think of any alternatives?
- Add some documentation to the section at the end of `spinsystem.html`.

**Comment by mdkrzyaniak** [comment]
The first thought that comes to mind is `zerofield` and `highfield` or `eigenbasis`

**Comment by mdkrzyaniak** [comment]
- I changed PopBasis to zerofield and eigenbasis. Still probably not completely ideal but better than it was.
-  I think I fully updated the documentation.
- added an additional syntax check in resfields and resfreqs
- I also included the proposed addition of D_ to which defines the ZFS as D and E/D, including tests and documentation.

**Comment by stestoll** [comment]
The addition of `D_` is a separate and orthogonal issue (#49). Please move to a separate PR.

**Comment by mdkrzyaniak** [comment]
So right now we have `Sys.PopMode`: `'zerofield'`, `'highfield'` and `'eigenbasis'`.
A more intuitive set might be: `'zerofield'`, `'non-Boltzmann'` and `'state overlap'`
Thoughts?

I still need to write a few more tests but I think this is getting close.

**Pull request closed without merging**
